name: MiniJobNow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  shared_preferences: ^2.2.2
  sensors_plus: ^4.0.2
  flutter_native_splash: ^2.4.6
  liquid_glass_renderer: ^0.1.1-dev.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/Artboard 1.svg
    - assets/icons/Artboard 2.svg
    - assets/icons/Artboard 3.svg
    - assets/icons/logo.png
    - assets/icons/branding.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#0D0D0D"
  image: "assets/icons/logo.png"
  branding: "assets/icons/branding.png"
